package com.wanxg.mynotes.core;

public enum UserManagerAction {
	REMEMBER_ME,
	SIGN_UP,
	SOCIAL_SIGN_UP,
	FIND_USER,
	FIND_USER_PROFILE,
	MANAGE_LOCAL_USER,
	UPDATE_USER_PASSWORD,
	MANAGE_USER_PROFILE,
	UPDATE_USER_PROFILE,
	MANAGE_TOKEN,
	DELETE_TOKEN,
	REISSUE_TOKEN,
}
